/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "pwm.h"//servo and uled control
#include "soil_sensor.h"//for soil sensor state machine
#include "timers.h"//timing 
#include "state_machine.h"//state_machine control of Application
#include "log.h"//debug 
#include "adc.h"//adc control
#include "spi.h"//spi control for lcd
#include "lcd.h"//lcd control commands

/* Test includes */
#include "test/test_pwm.h"
#include "test/test_soil_sensor.h"
#include "test/test_adc.h"
#include "test/test_state_machine.h"

//#define RUN_TESTS

/* 1 second interval led flash to show that loop is working
 * @param none 
 * @return none
 */
void heartbeat_led(void);

int main(void)
{
	/* You can use the Command Shell Console in STM32CubeIDE or an
	 * external program such as Putty or TeraTerm to view printf output.
	 * The settings are: Baud: 9600, Parity: None, Stop Bits: 1 with
	 * the ST-Link COM port setting.
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 */
	LOG("\r\nAutomatic Watering Plant System!\r\n");

	/* Initialization */
	init_uled();
	init_PWM_SERVO();
	init_systick();
	soil_sensor_init();//adc hardware init and gpio init for soil moisture sensor
	set_uled(OFF);
#ifdef LCD
    LOG("Initializing LCD\r\n");
    //Init SPI2 (PC3 MOSI, PB10 SCK, PC9 latch)
    spi2_init(4); //clk divider of 4 to get to 48/4 to 12 
    LOG("SPI2 initialized\r\n");
	//Init LCD
    lcd_init();
    LOG("LCD initialized\r\n");
    //Clear screen
    lcd_clear();
    lcd_printf(0, 0, "%s", "Hello World!");
    LOG("Printed 'Hello World!' to LCD\r\n");
#endif

	LOG("Initialization Complete\r\n");
	
#ifdef RUN_TESTS
	/* Run unit tests if enabled */
	LOG("\r\n========== RUNNING UNIT TESTS ==========\r\n");
	int test_result = 0;
	test_result |= test_pwm();
	test_result |= test_soil_sensor();
	test_result |= test_adc();
	test_result |= test_state_machine();
	LOG("\r\n========== UNIT TESTS COMPLETE ==========\r\n");
	if (test_result == 0)
	{
		LOG("All tests PASSED!\r\n");
		set_uled(ON);
	}
	else
	{
		LOG("Some tests FAILED!\r\n");
	}
	//in case tests fail dont want to potentially break hardware
	return test_result;
#endif
    
    /* Loop forever */
	LOG("Main Loop Starting\r\n");
	reset_timer(TIMER_START_ID);//starts timer
	reset_timer(TIMER_START_ULED_ID);//starts timer
	reset_timer(TIMER_SOIL_SAMPLING_ID);//starts timer
	soil_sensor_begin_measurement();//start first measurement
	for(;;)
	{
		soil_measure_fsm();//toggles power to the soil sensor based on state
		water_fsm_run();//watering fsm controls watering service
		heartbeat_led();//heartbeat_led to visually see if something critical is wrong
	}
}

/* 1 second interval led flash to show that loop is working
 * @param none 
 * @return none
 */
void heartbeat_led(void)
{
	static ticktime_t timer_heartbeat;
	static uint8_t blink = 0;
	//heartbeat uled every second
	timer_heartbeat = get_timer(TIMER_START_ULED_ID);
	if(timer_heartbeat >= ONE_SECOND_TICKS)//1second interrupt
	{
		blink = !blink;//toggle uled flag
		reset_timer(TIMER_START_ULED_ID);//reset timer reference
		set_uled(blink);//toggle uled flag
	}
}
