/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "gpio.h"
#include "timers.h"//timing 
#include "state_machine.h"//state_machine functions and #defines
#include "log.h"//debug 

int main(void)
{
	/* You can use the Command Shell Console in STM32CubeIDE or an
	 * external program such as Putty or TeraTerm to view printf output.
	 * The settings are: Baud: 9600, Parity: None, Stop Bits: 1 with
	 * the ST-Link COM port setting.
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 */
	LOG("Hello World !\r\n");

	/* Initialization */
	init_uled();
	init_systick();
	init_led_status();
	set_uled(OFF);
	
    /* Loop forever */
	LOG("Main Loop Starting\r\n");
	reset_timer(TIMER_START_ID);//starts timer
	reset_timer(TIMER_START_ELED_ID);//starts timer
	reset_timer(TIMER_START_ULED_ID);//starts timer
	for(;;)
	{
		estop_handler();//checks for estop button and sets state machine
		first_entry();//checks for first entry into state and resets elapsed timer in a new state
		state_logic();//executes state logic with timers and brightness levels and blinking
		updateBusState();//updates state to next state
	}
}
