/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "pwm.h"//servo and uled control
#include "soil_sensor.h"//for soil sensor state machine
#include "timers.h"//timing 
#include "state_machine.h"//state_machine control of Application
#include "log.h"//debug 
#include "adc.h"//adc control
#include "spi.h"//spi control for lcd
#include "lcd.h"//lcd control

//#define SERVO
//#define SOIL_SENSOR
#define LCD

int main(void)
{
	/* You can use the Command Shell Console in STM32CubeIDE or an
	 * external program such as Putty or TeraTerm to view printf output.
	 * The settings are: Baud: 9600, Parity: None, Stop Bits: 1 with
	 * the ST-Link COM port setting.
	 * Clocks: Processor = 48 Mhz. AHB = 48 MHz. APB = 24 MHz.
	 */
	LOG("Hello World!\r\n");

	/* Initialization */
	init_uled();
	init_PWM_SERVO();
	init_systick();
	soil_sensor_init();//adc hardware init and gpio init for soil moisture sensor
	set_uled(OFF);
	LOG("Initialization Complete\r\n");
	
    /* Loop forever */
	LOG("Main Loop Starting\r\n");
	reset_timer(TIMER_START_ID);//starts timer
	reset_timer(TIMER_START_ULED_ID);//starts timer
	reset_timer(TIMER_SOIL_SAMPLING_ID);//starts timer
	uint8_t blink = 0;
#ifdef SERVO
	uint8_t test  = 0;
#endif
#ifdef SOIL_SENSOR
	uint16_t adc_value = 0;
	uint16_t last_raw = 0;
    uint8_t  last_pct = 0;
	soil_sensor_begin_measurement();//start first measurement
#endif
	ticktime_t local_timer_heartbeat = 0;
	for(;;)
	{
		//heartbeat uled every second
		local_timer_heartbeat = get_timer(TIMER_START_ULED_ID);
		if(local_timer_heartbeat >= ONE_SECOND_TICKS)//1second interrupt
		{
			blink = !blink;//toggle uled flag
			reset_timer(TIMER_START_ULED_ID);//reset timer reference
			set_uled(blink);//toggle uled flag
		}
		/*
		
		
		
		
		*/
#ifdef SOIL_SENSOR
		soil_measure_fsm();//run soil sensor state machine
		if(soil_sensor_is_ready())
		{
			//new data available
			adc_value = soil_sensor_get_raw();
			if(adc_value != last_raw)//if didn't change, don't log
			{
				last_raw = adc_value;
				last_pct = soil_sensor_get_percent();
				LOG("Soil Moisture: Raw=%u, Percent=%u%%\r\n", last_raw, last_pct);
			}
			soil_sensor_begin_measurement();//start next measurement
		}
#endif
		/*
		
		
		
		
		*/
#ifdef LCD
		LOG("LCD Update Placeholder\r\n");
#endif
		/*
		
		
		
		
		*/
#ifdef SERVO
		if(!test)
		{
			servo_set_angle(270);
			test = !test;
		}
#endif
	}
}
